In [2]:
import pandas as pd

In [19]:
# Cleaning data - Handle Missing Value
df = pd.read_csv("raw_data.csv")

df.isnull()
df.isna()   #same as isnull()

df.isnull().sum()

df.dropna()  #row drop
df.dropna(axis = 1)  #column drop

df.fillna(0)

cleaned_data = df.copy()
cleaned_data["age"] = df["age"].fillna(df["age"].mean())

df.ffill()
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [6]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [25]:
#Handle Duplicates

df[["country", "gender"]].duplicated()
df2 = df.copy()

df.drop_duplicates(inplace = True)

In [26]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [30]:
#Data Types

df.dtypes
df2 = df.copy()

df2 = df2.fillna(0)
df2 =df2["age"].astype("int64").copy()
df2.dtypes

dtype('int64')

In [31]:
aqi_data = pd.read_csv ("globalAirQuality.csv")
aqi_data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [34]:
date_str = pd.Series([pd.to_datetime("2026-12-31")])
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

In [39]:
df['gender'].str.lower()

df["name"].str.split(" ")

df["country"].str.contains("india", case= False)

0     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [1]:
import pandas as pd
df = pd.read_csv("raw_data.csv")

In [2]:
#Feature Engineering
df2 = df.copy()

df2["tax"] = df2["income"].apply(lambda x : "20%" if x>= 50000 else "10%")

gender_map = {"Male" : "M", "Female": "F", "Unknown": "U"}
df2["gender"].map(gender_map)

df2.assign(new_income = df2["income"] * 1.1)

    id          name   age country   gender   income  tax  new_income
0    1      John Doe  29.0     USA     Male  55000.0  20%     60500.0
1    1      John Doe  29.0     USA     Male  55000.0  20%     60500.0
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%     68200.0
3    3          Alex   NaN     USA  Unknown  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%         NaN
5    5        Li Wei  27.0   China     Male  51000.0  20%     56100.0
6    6           NaN  45.0   India   Female  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%     63800.0

In [ ]:
# Transformation
df2.rename({"Income" : "Salary"})
d